#!/bin/bash
# This script was generated by ChatGPT from OpenAI and should be used with caution for many reasons.
# It is designed to be a helpful tool, but it is not perfect and may not always provide accurate or complete information. 
# Additionally, its responses are not intended to be used as legal, medical, or professional advice, 
# and it should not be relied upon as such. 
# Use of this script is at your own risk, and I cannot be held responsible for any errors or omissions it may contain. 
# By using this script, you acknowledge and agree to these terms.


# Stop the script if any command returns a non-zero exit status
set -e

# Define a directory where we will store the textfile that keeps track of
# downloaded PDFs
PDF_TRACKER_DIR="/tmp/pdf-tracker"

# Create the directory if it doesn't exist
mkdir -p "$PDF_TRACKER_DIR" || {
    echo "Error: Failed to create directory $PDF_TRACKER_DIR" >&2
    exit 1
}

# Use inotifywait to monitor the directory where PDFs are downloaded
# and open any new PDFs with Okular as they are downloaded
inotifywait -m -e create --format '%f' "$HOME/Downloads" | while read pdf; do
    if [[ $pdf == *.pdf ]]; then
	# Wait for the file to be completely downloaded before opening it
	# The maximum wait time is 1.3 seconds
	while [[ ! -s "$PDF_TRACKER_DIR/$pdf" ]] && [[ $i -lt 13 ]]; do
    	  sleep 0.1
    	  i=$(( i + 1 ))
	done
	# mv the downloaded file into the tmp dir
	mv "$HOME/Downloads/$pdf" $PDF_TRACKER_DIR	

        zathura "$PDF_TRACKER_DIR/$pdf" &
    fi
done

